---
include:
  # Left half with OLED
  - board: nice_nano_v2
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Corne_Oled\"
    artifact-name: nice_corne_left_oled
    snippet: studio-rpc-usb-uart

  # Right half with OLED  
  - board: nice_nano_v2
    shield: corne_right nice_oled
    artifact-name: nice_corne_right_oled

  # Settings reset (useful for troubleshooting)
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset